spring:
  datasource:
    url: jdbc:mysql://localhost:3306/c?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver